export enum Icon {
  Profile = 'profile',
  Bed = 'bed',
  Menu = 'menu',
  Arrow_right = 'arrow_right',
  Close = 'close',
  Arrow_left = 'arrow_left',
  Person = 'person',
  Right = 'right',
  Up = 'up',
  Down = 'down',
  Left = 'left',
  Check = 'check',
  Size = 'size',
  Luxurycar = 'luxurycar',
  Rrain = 'train',
  Car = 'car',
}
