// Generated by https://quicktype.io

import { BaseRes, User } from './Common';

export type LoginReq = {
  email: string;
  password: string;
};

export interface LoginRes extends BaseRes<User> {
  token: string;
}



