// Generated by https://quicktype.io

import { BaseRes, Result } from './Common';

export type LoginReq = {
  email: string;
  password: string;
};

export interface LoginRes extends BaseRes<Result> {}



