// Generated by https://quicktype.io

import { BaseRes } from './Common';

export interface RoomRes extends BaseRes<Room[]> {}
export interface DetailRes extends BaseRes<Room> {}

export type Room = {
  name: string;
  description: string;
  imageUrl: string;
  imageUrlList: string[];
  areaInfo: string;
  bedInfo: string;
  maxPeople: number;
  price: number;
  status: number;
  layoutInfo: Info[];
  facilityInfo: Info[];
  amenityInfo: Info[];
  _id: string;
  createdAt: Date;
  updatedAt: Date;
}

export type Info = {
  title: string;
  isProvide: boolean;
}
